name: Linting

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  spLinter:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Linting with make
        run: make lint
